---
deployment:
  tasks:
    - export DEPLOYPATH=/home/peke6862/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp team-details.php $DEPLOYPATH
    - /bin/cp team.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    
    - /bin/cp blog-details.php $DEPLOYPATH
    - /bin/cp blog.php $DEPLOYPATH
    - /bin/cp blog-standard.php $DEPLOYPATH
    
    - /bin/cp donation-details.php $DEPLOYPATH
    - /bin/cp donate-now.php $DEPLOYPATH
    - /bin/cp donation.php $DEPLOYPATH
    
    - /bin/cp event-details.php $DEPLOYPATH
    - /bin/cp event-grid.php $DEPLOYPATH
    - /bin/cp event.php $DEPLOYPATH
    
    - /bin/cp gallery.php $DEPLOYPATH

    - /bin/cp contact.php $DEPLOYPATH
    
    - /bin/cp faq.php $DEPLOYPATH
    - /bin/cp become-volunteer.php $DEPLOYPATH
    - /bin/cp 404.php $DEPLOYPATH

    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R archives $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH